### ISSUE TITLE
Not redirecting to auth php file 

### ISSUE THREAD

**Issue by vivek-sethia** [denzilferreira/aware-server#3]
I was debugging the PHP code and found that in dashboard.php the following line of code causing the problem
   
`redirect(base_url('index.php/auth'))`

The redirection happens to the and URL changes in the browser `( https://mydomain/e/index.php/auth) ` but there is nothing after that. When I printed a text before it and returned from the function, the text is shown in the browser. The code snippet which I tried:

```
print 'Inside dashboard.php'
return;
redirect(base_url('index.php/auth'))
```

But when I debugged inside auth.php and print anything, it was never shown.  This leads to the conclusion that the auth.php file is not called.

Any ideas on what could be the reason behind this behavior. 

`Server version: Apache/2.4.7 (Ubuntu)`

**Comment by denzilferreira** [comment]
This was a failed download.
