### ISSUE TITLE
 Cannot modify header information  and Undefined offset error

### ISSUE THREAD

**Issue by risoms** [denzilferreira/aware-server#4]
I'm attempting to host an aware-server dashboard on my server but after following the directions here: http://www.awareframework.com/hosting-your-own-aware-dashboard/. I recieve the errors in the screen capture below. Do you have any idea why this may be happening?

![screen_capture](https://user-images.githubusercontent.com/10383917/27197368-8f2438e2-51d3-11e7-9ba4-7b29acb3e248.png)

**Comment by denzilferreira** [comment]
Hum... did you enable compression in CodeIgniter? It may be that your Apache does not have support for gzip enabled?
